filter:
    excluded_paths:
        - 'vendor/*'
        - 'app/*'
        - 'web/*'

before_commands:
    - "composer install --prefer-source"

tools:
    php_cpd: true
    php_pdepend: true
    php_mess_detector: true
    php_cs_fixer:
        config:
            level: psr2
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_loc: true
